# Generated by Django 3.0.4 on 2020-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTypeId', models.IntegerField()),
                ('acceptedAnswerId', models.IntegerField(null=True)),
                ('parentId', models.IntegerField(null=True)),
                ('ownerUserId', models.IntegerField(null=True)),
                ('score', models.IntegerField()),
                ('viewCount', models.IntegerField(null=True)),
                ('lastEditorUserId', models.IntegerField(null=True)),
                ('answerCount', models.IntegerField(null=True)),
                ('commentCount', models.IntegerField(default=0)),
                ('favoriteCount', models.IntegerField(null=True)),
                ('body', models.TextField()),
                ('ownerDisplayName', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('tags', models.TextField(null=True)),
                ('creationDate', models.DateTimeField()),
                ('closedDate', models.DateTimeField(null=True)),
                ('lastEditDate', models.DateTimeField(null=True)),
                ('lastActivityDate', models.DateTimeField()),
            ],
        ),
    ]
